### ISSUE TITLE
thamos fails with the current client update

### ISSUE THREAD

**Issue by fridex** [thoth-station/thamos#1073]
**Describe the bug**

```
2022-03-07 16:54:33,647 [1187740] CRITICAL root: Traceback (most recent call last):
  File "/home/fpokorny/.local/bin/thamos", line 8, in <module>
    sys.exit(cli())
  File "/home/fpokorny/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/rich_click/rich_click.py", line 600, in main
    return super().main(*args, standalone_mode=False, **kwargs)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fpokorny/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/cli.py", line 139, in wrapper
    return func(*args, **kwargs)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/cli.py", line 743, in advise
    results = thoth_advise_here(
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/lib.py", line 707, in advise_here
    return advise(
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/lib.py", line 118, in wrapper
    result = func(api_client, *args, **kwargs)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/lib.py", line 595, in advise
    response = _retrieve_analysis_result(
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/lib.py", line 276, in _retrieve_analysis_result
    return retrieve_func(analysis_id)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/swagger_client/thoth/advise_api.py", line 53, in get_advise_python
    (data) = self.get_advise_python_with_http_info(analysis_id, **kwargs)  # noqa: E501
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/swagger_client/thoth/advise_api.py", line 112, in get_advise_python_with_http_info
    return self.api_client.call_api(
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 316, in call_api
    return self.__call_api(resource_path, method,
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 160, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 232, in deserialize
    return self.__deserialize(data, response_type)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 271, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 618, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 271, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 618, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 271, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 618, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 248, in __deserialize
    return [self.__deserialize(sub_data, sub_kls)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 248, in <listcomp>
    return [self.__deserialize(sub_data, sub_kls)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 271, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 618, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 248, in __deserialize
    return [self.__deserialize(sub_data, sub_kls)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 248, in <listcomp>
    return [self.__deserialize(sub_data, sub_kls)
  File "/home/fpokorny/.local/lib/python3.8/site-packages/thamos/swagger_client/api_client.py", line 260, in __deserialize
    klass = getattr(thamos.swagger_client.models, klass)
AttributeError: module 'thamos.swagger_client.models' has no attribute 'list'
```

**To Reproduce**
1. run `thamos advise` against prod with the current master
4. see the error reported

**Comment by fridex** [comment]
/priority critical-urgent
/assign

This prevents from releasing any new thamos.
