### ISSUE TITLE
Pipfile is empty

### ISSUE THREAD

**Issue by goern** [thoth-station/thamos#127]
**Describe the bug**
after some exception was raised, the pipfile is empty.

**To Reproduce**
Have an exception raised while writing to Pipfile:
```
2019-03-26 13:48:56,268 [25830] CRITICAL root: Traceback (most recent call last):
  File "/home/goern/.local/lib/python3.7/site-packages/contoml/elements/abstracttable.py", line 22, in _enumerate_items
    yield next(non_metadata), next(non_metadata)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/goern/.local/bin/thamos", line 11, in <module>
    load_entry_point('thamos==0.3.1', 'console_scripts', 'thamos')()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 721, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1065, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 894, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/goern/.local/lib/python3.7/site-packages/thamos/cli.py", line 355, in advise
    _write_pipfiles(pipfile, pipfile_lock)
  File "/home/goern/.local/lib/python3.7/site-packages/thamos/cli.py", line 111, in _write_pipfiles
    toml.dump(pipfile, "Pipfile", prettify=False)
  File "/home/goern/.local/lib/python3.7/site-packages/contoml/__init__.py", line 75, in dump
    fp.write(dumps(obj, prettify=prettify))
  File "/home/goern/.local/lib/python3.7/site-packages/contoml/__init__.py", line 58, in dumps
    f[k] = v
  File "/home/goern/.local/lib/python3.7/site-packages/contoml/file/file.py", line 51, in __setitem__
    self._elements.append(element_factory.create_table(value))
  File "/home/goern/.local/lib/python3.7/site-packages/contoml/elements/factory.py", line 134, in create_table
    table_element = TableElement([create_newline_element()])
  File "/home/goern/.local/lib/python3.7/site-packages/contoml/elements/table.py", line 22, in __init__
    self._check_for_duplicate_keys()
  File "/home/goern/.local/lib/python3.7/site-packages/contoml/elements/table.py", line 25, in _check_for_duplicate_keys
    if len(set(self.keys())) < len(self.keys()):
  File "/home/goern/.local/lib/python3.7/site-packages/contoml/elements/abstracttable.py", line 32, in keys
    return tuple(key for (key, _) in self.items())
  File "/home/goern/.local/lib/python3.7/site-packages/contoml/elements/abstracttable.py", line 32, in <genexpr>
    return tuple(key for (key, _) in self.items())
  File "/home/goern/.local/lib/python3.7/site-packages/contoml/elements/abstracttable.py", line 25, in items
    for (key_i, key), (value_i, value) in self._enumerate_items():
RuntimeError: generator raised StopIteration

```

**Expected behavior**
Pipfile is not empty even on exception

**Additional context**
n/a

**Comment by fridex** [comment]
Check your contoml version, I cannot reproduce this:
```
>>> import contoml
>>> contoml.__version__
'0.32'
```

**Comment by goern** [comment]
0.32

**Comment by fridex** [comment]
Can you try it from within virtualenv?

```
cd thamos/
pipenv shell
cd examples/lockdown/
PYTHONPATH=../.. ../../thamos-cli advise
```

**Comment by goern** [comment]
```
2019-03-26 14:11:43,223 [6259] INFO     thamos: No Pipfile.lock found
2019-03-26 14:11:44,212 [6259] CRITICAL root: Traceback (most recent call last):
  File "/tmp/tmp.e6G0TPiklb/thamos/thamos/config.py", line 212, in api_discovery
    response.raise_for_status()
  File "/home/goern/.local/share/virtualenvs/thamos-6Qm7hSwW/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://test.thoth-station.ninja/api/v1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/goern/.local/share/virtualenvs/thamos-6Qm7hSwW/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/goern/.local/share/virtualenvs/thamos-6Qm7hSwW/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/goern/.local/share/virtualenvs/thamos-6Qm7hSwW/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/goern/.local/share/virtualenvs/thamos-6Qm7hSwW/lib/python3.6/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/home/goern/.local/share/virtualenvs/thamos-6Qm7hSwW/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 773, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)
```

**Comment by fridex** [comment]
>
```
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://test.thoth-station.ninja/api/v1
```

revert #125
