### ISSUE TITLE
Error in showing results from an analysis

### ISSUE THREAD

**Issue by fridex** [thoth-station/thamos#133]
```
2019-04-15 12:34:50,549 [1] CRITICAL root: Traceback (most recent call last):
  File "/usr/local/bin/thamos", line 11, in <module>
    load_entry_point('thamos==0.3.1', 'console_scripts', 'thamos')()
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/thamos/cli.py", line 349, in advise
    _print_report(result["stack_info"], json_output=json_output)
  File "/usr/local/lib/python3.6/site-packages/thamos/cli.py", line 179, in _print_report
    for item in report:
TypeError: 'NoneType' object is not iterable
```

Reproducer in `adviser-4ff2186be5240330`.

**Comment by fridex** [comment]
Already fixed in the current master branch.
