### ISSUE TITLE
thamos is missing dependency invectio

### ISSUE THREAD

**Issue by goern** [thoth-station/thamos#149]
**Describe the bug**
```
 goern@t540p  ~/W/t/t/e/lockdown   fix/url-minor-stuff ?  thamos --version                       
Traceback (most recent call last):
  File "/home/goern/.local/bin/thamos", line 11, in <module>
    load_entry_point('thamos==0.4.1', 'console_scripts', 'thamos')()
  File "/home/goern/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/goern/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/home/goern/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/goern/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/goern/.local/lib/python3.7/site-packages/thamos/cli.py", line 35, in <module>
    from thamos.lib import advise as thoth_advise
  File "/home/goern/.local/lib/python3.7/site-packages/thamos/lib.py", line 33, in <module>
    from invectio import gather_library_usage
ModuleNotFoundError: No module named 'invectio'
 goern@t540p  ~/W/t/t/e/lockdown   fix/url-minor-stuff ?  pip show thamos                          
Name: thamos
Version: 0.4.1
Summary: A CLI tool and library for interacting with Thoth
Home-page: UNKNOWN
Author: Fridolin Pokorny
Author-email: fridolin@redhat.com
License: GPLv3+
Location: /home/goern/.local/lib/python3.7/site-packages
Requires: contoml, certifi, six, python-dateutil, setuptools, urllib3, daiquiri, click, distro, thoth-analyzer, yaspin, texttable, pyyaml, requests, termcolor
Required-by: 
```

**To Reproduce**
1. `pip install thamos`
2. `thamos --verion`

**Expected behavior**
print `0.4.1`

**Additional context**
n/a

**Comment by fridex** [comment]
Ah, sorry about this. I've released version without invectio, the patch release in https://github.com/thoth-station/thamos/pull/148 was not propagated by zuul to pypi. I've released 0.4.2 manually, this should be fixed - https://pypi.org/project/thamos/0.4.2/.

**Comment by goern** [comment]
using `./build-container-image.sh` I receive:

```
Collecting invectio (from thamos)
  Downloading https://files.pythonhosted.org/packages/fb/04/fe37216069ffd7328b90a2b751da3dad48514b1bc85b74e02aab394180e5/invectio-0.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-f49415s7/invectio/setup.py", line 39, in <module>
        cmdclass={"test": Test},
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 495, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 111, in parse_configuration
        meta.parse()
      File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 397, in parse
        section_parser_method(section_options)
      File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 370, in parse_section
        self[name] = value
      File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 174, in __setitem__
        value = parser(value)
      File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 463, in _parse_version
        version = self._parse_attr(value, self.package_dir)
      File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 320, in _parse_attr
        module = import_module(module_name)
      File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/pip-build-f49415s7/invectio/invectio/__init__.py", line 25, in <module>
        from .lib import gather_library_usage
      File "/tmp/pip-build-f49415s7/invectio/invectio/lib.py", line 24, in <module>
        import attr
    ModuleNotFoundError: No module named 'attr'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-f49415s7/invectio/
error while running runtime: exit status 1

```

**Comment by goern** [comment]
ah, seems to be related to https://github.com/thoth-station/invectio/pull/8

**Comment by fridex** [comment]
Fixed. Closing.
