### ISSUE TITLE
thamos assumes https connection

### ISSUE THREAD

**Issue by goern** [thoth-station/thamos#150]
**Describe the bug**
```
 thamos --verbose advise --debug --force
2019-05-30 11:04:56,416 [14607] DEBUG    thamos: Debug mode turned on
2019-05-30 11:04:56,416 [14607] DEBUG    thamos: Thamos version: '0.4.1'
2019-05-30 11:04:56,417 [14607] DEBUG    thamos: Loading Pipfile in '/tmp/tmp.mkfCXFopJa'
2019-05-30 11:04:56,417 [14607] DEBUG    thamos: Loading Pipfile.lock in '/tmp/tmp.mkfCXFopJa'
2019-05-30 11:07:10,319 [14607] CRITICAL root: Traceback (most recent call last):
  File "/home/goern/.local/share/virtualenvs/tmp.mkfCXFopJa-i71Q9YP4/lib/python3.7/site-packages/thamos/config.py", line 212, in api_discovery
    response.raise_for_status()
  File "/home/goern/.local/share/virtualenvs/tmp.mkfCXFopJa-i71Q9YP4/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://stage.thoth-station.ninja/api/v1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/goern/.local/share/virtualenvs/tmp.mkfCXFopJa-i71Q9YP4/lib/python3.7/site-packages/thamos/config.py", line 223, in api_discovery
    response.raise_for_status()
  File "/home/goern/.local/share/virtualenvs/tmp.mkfCXFopJa-i71Q9YP4/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://stage.thoth-station.ninja/api/v1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/goern/.local/share/virtualenvs/tmp.mkfCXFopJa-i71Q9YP4/bin/thamos", line 10, in <module>
    sys.exit(cli())
  File "/home/goern/.local/share/virtualenvs/tmp.mkfCXFopJa-i71Q9YP4/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/goern/.local/share/virtualenvs/tmp.mkfCXFopJa-i71Q9YP4/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/goern/.local/share/virtualenvs/tmp.mkfCXFopJa-i71Q9YP4/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/goern/.local/share/virtualenvs/tmp.mkfCXFopJa-i71Q9YP4/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/goern/.local/share/virtualenvs/tmp.mkfCXFopJa-i71Q9YP4/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/goern/.local/share/virtualenvs/tmp.mkfCXFopJa-i71Q9YP4/lib/python3.7/site-packages/thamos/cli.py", line 341, in advise
    no_static_analysis=no_static_analysis,
  File "/home/goern/.local/share/virtualenvs/tmp.mkfCXFopJa-i71Q9YP4/lib/python3.7/site-packages/thamos/lib.py", line 64, in wrapper
    thoth_config.api_discovery(host)
  File "/home/goern/.local/share/virtualenvs/tmp.mkfCXFopJa-i71Q9YP4/lib/python3.7/site-packages/thamos/config.py", line 232, in api_discovery
    ) from exc
thamos.exceptions.NoApiSupported: Server does not support API v1 required by Thamos client
```

**To Reproduce**
1. `thamos advise ...`

**Expected behavior**
just work

**Additional context**
n/a

**Comment by goern** [comment]
btw, with test env the behavior is different:

```
2019-05-30 11:15:24,055 [15583] DEBUG    thamos: Debug mode turned on
2019-05-30 11:15:24,055 [15583] DEBUG    thamos: Thamos version: '0.4.1'
2019-05-30 11:15:24,056 [15583] DEBUG    thamos: Loading Pipfile in '/tmp/tmp.mkfCXFopJa'
2019-05-30 11:15:24,056 [15583] DEBUG    thamos: Loading Pipfile.lock in '/tmp/tmp.mkfCXFopJa'
2019-05-30 11:15:25,515 [15583] WARNING  thamos.config: Using insecure connection to API service, please contact service provider to install TLS in order to secure network traffic
2019-05-30 11:15:25,516 [15583] DEBUG    thamos.lib: Using API: http://test.thoth-station.ninja/api/v1
```

**Comment by fridex** [comment]
It first performed api discovery using https:

```
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://stage.thoth-station.ninja/api/v1
```

as it was not available, it performed fallback to raw http:

```
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://stage.thoth-station.ninja/api/v1
```

Both returned 503. It looks like the user-api service is/was down?

**Comment by harshad16** [comment]
@fridex the **stage.thoth-station.ninja** is not routed to user-api service at stage env in PSI cluster yet.
We have a trello card associated with this https://trello.com/c/cTekzKDs/597-route-the-domain-hostname-to-stage-psi-cluster.
update the route should the issue.

**Comment by fridex** [comment]
@harshad16 That makes sense, I see user-api being scaled down to zero on the old upshift deployment - hence 503 reported by openshift router. Thanks!

**Comment by goern** [comment]
@harshad16 this should be fixed with the done DNS updates, right?!

**Comment by harshad16** [comment]
yes @goern .
This issue is fixed after the route 53 configuration of `stage.thoth-station.ninja`.
Closing the issue.
