### ISSUE TITLE
No python file -> "Nothing to do"

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/thamos#151]
**Describe the bug**
```
(kebechet_testing) [kpostlet@localhost kebechet_testing]$ thamos --verbose advise --debug
2019-05-30 11:17:46,842 [3984] DEBUG    thamos: Debug mode turned on
2019-05-30 11:17:46,842 [3984] DEBUG    thamos: Thamos version: '0.4.1'
2019-05-30 11:17:46,843 [3984] DEBUG    thamos: Loading Pipfile in '/home/kpostlet/demos/kebechet_testing'
2019-05-30 11:17:46,843 [3984] DEBUG    thamos: Loading Pipfile.lock in '/home/kpostlet/demos/kebechet_testing'
2019-05-30 11:17:47,338 [3984] WARNING  thamos.config: Using insecure connection to API service, please contact service provider to install TLS in order to secure network traffic
2019-05-30 11:17:47,339 [3984] DEBUG    thamos.lib: Using API: http://test.thoth-station.ninja/api/v1
2019-05-30 11:17:47,348 [3984] INFO     thamos.lib: Performing static analysis
2019-05-30 11:17:47,355 [3984] CRITICAL root: Traceback (most recent call last):
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/bin/thamos", line 10, in <module>
    sys.exit(cli())
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/thamos/cli.py", line 341, in advise
    no_static_analysis=no_static_analysis,
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/thamos/lib.py", line 71, in wrapper
    result = func(ApiClient(configuration=config), *args, **kwargs)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/thamos/lib.py", line 187, in advise
    library_usage = _get_static_analysis()
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/thamos/lib.py", line 132, in _get_static_analysis
    library_usage = gather_library_usage(".", ignore_errors=True)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/invectio/lib.py", line 151, in gather_library_usage
    raise FileNotFoundError(f"No files to process for {str(path)!r}")
FileNotFoundError: No files to process for '.'

(kebechet_testing) [kpostlet@localhost kebechet_testing]$ ls
Pipfile  Pipfile.lock  README.md  requirements.txt
```

**To Reproduce**
1. create directory with Pipfile and Pipfile.lock
2. `thamos advise`

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by fridex** [comment]
You are missing some sources to perform static source code analysis (an empty *.py file would work). You will also need .thoth.yaml file ([example](https://github.com/thoth-station/adviser/blob/master/.thoth.yaml)) to get information to which host the request should go to.

Anyway, we will need a more user-friendly message for this.
