### ISSUE TITLE
Invalid value for `metadata`, must not be `None`

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/thamos#154]
**Describe the bug**
```
(kebechet_testing) [kpostlet@localhost kebechet_testing]$ thamos --verbose advise --debug --force
2019-05-31 15:08:14,877 [28609] DEBUG    thamos: Debug mode turned on
2019-05-31 15:08:14,877 [28609] DEBUG    thamos: Thamos version: '0.4.2'
2019-05-31 15:08:14,877 [28609] DEBUG    thamos: Loading Pipfile in '/home/kpostlet/demos/kebechet_testing'
2019-05-31 15:08:14,877 [28609] DEBUG    thamos: Loading Pipfile.lock in '/home/kpostlet/demos/kebechet_testing'
2019-05-31 15:08:15,178 [28609] WARNING  thamos.config: Using insecure connection to API service, please contact service provider to install TLS in order to secure network traffic
2019-05-31 15:08:15,179 [28609] DEBUG    thamos.lib: Using API: http://test.thoth-station.ninja/api/v1
2019-05-31 15:08:15,189 [28609] INFO     thamos.lib: Performing static analysis
2019-05-31 15:08:15,190 [28609] WARNING  thamos.lib: No library usage was aggregated - no Python sources found
2019-05-31 15:08:15,190 [28609] DEBUG    thamos.lib: Library usage:
{}
2019-05-31 15:08:15,885 [28609] INFO     thamos.lib: Successfully submitted advise analysis 'adviser-4c7d5f6785bff641' to 'http://test.thoth-station.ninja/api/v1'
2019-05-31 15:08:15,940 [28609] DEBUG    thamos.lib: Waiting for 'adviser-4c7d5f6785bff641' to finish for 0.5 seconds (state: waiting)
2019-05-31 15:08:16,492 [28609] DEBUG    thamos.lib: Waiting for 'adviser-4c7d5f6785bff641' to finish for 1.0 seconds (state: waiting)
2019-05-31 15:08:17,545 [28609] DEBUG    thamos.lib: Waiting for 'adviser-4c7d5f6785bff641' to finish for 2.0 seconds (state: waiting)
2019-05-31 15:08:19,608 [28609] DEBUG    thamos.lib: Waiting for 'adviser-4c7d5f6785bff641' to finish for 4.0 seconds (state: waiting)
2019-05-31 15:08:23,734 [28609] DEBUG    thamos.lib: Waiting for 'adviser-4c7d5f6785bff641' to finish for 8.0 seconds (state: running)
2019-05-31 15:08:31,792 [28609] DEBUG    thamos.lib: Waiting for 'adviser-4c7d5f6785bff641' to finish for 10 seconds (state: running)
2019-05-31 15:08:41,867 [28609] DEBUG    thamos.lib: Retrieving adviser result for 'adviser-4c7d5f6785bff641'
2019-05-31 15:08:42,216 [28609] CRITICAL root: Traceback (most recent call last):
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/bin/thamos", line 10, in <module>
    sys.exit(cli())
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/thamos/cli.py", line 341, in advise
    no_static_analysis=no_static_analysis,
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/thamos/lib.py", line 71, in wrapper
    result = func(ApiClient(configuration=config), *args, **kwargs)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/thamos/lib.py", line 249, in advise
    api_instance.get_advise_python, response.analysis_id
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/thamos/lib.py", line 117, in _retrieve_analysis_result
    return retrieve_func(analysis_id)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/thamos/swagger_client/thoth/advise_api.py", line 53, in get_advise_python
    (data) = self.get_advise_python_with_http_info(analysis_id, **kwargs)  # noqa: E501
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/thamos/swagger_client/thoth/advise_api.py", line 126, in get_advise_python_with_http_info
    collection_formats=collection_formats)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 321, in call_api
    _preload_content, _request_timeout)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 160, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 232, in deserialize
    return self.__deserialize(data, response_type)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 271, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 616, in __deserialize_model
    instance = klass(**kwargs)
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/thamos/swagger_client/models/analysis_result_response.py", line 47, in __init__
    self.metadata = metadata
  File "/home/kpostlet/.local/share/virtualenvs/kebechet_testing-yrvOpqym/lib/python3.6/site-packages/thamos/swagger_client/models/analysis_result_response.py", line 69, in metadata
    raise ValueError("Invalid value for `metadata`, must not be `None`")  # noqa: E501
ValueError: Invalid value for `metadata`, must not be `None`
```

**To Reproduce**
1. thamos --verbose advise --debug

**Expected behavior**
Just works

**Screenshots**

**Additional context**
Edit: occurs for all advise jobs

**Comment by KPostOffice** [comment]
This actually occurs for every advise job

**Comment by fridex** [comment]
Result API had for some reason propagated wrong deployment name, it stored results to stage prefix on Ceph instead of the test one. It picked configuration correctly from configmap, but it looks to me that this configuration was adjusted later after deployment and redeployment of result-api did not happen. User API expected results on Ceph under a correct prefix. Hence user API reported 202 (analysis still in progress) even though results were expected ([this branch of if statement](https://github.com/thoth-station/user-api/blob/14a5c22887f1fcd2a74945418566850e9d17a0d7/thoth/user_api/api_v1.py#L491)).

I've redeployed result API so it picks correct configuration. Let me know if the issue persists.

**Comment by fridex** [comment]
To make sure you use some packages which we have ingested and you get some response, this is configuration I verified in test env and gives back some results:

```console
$ ls -a                                                                                                                                                                                       
.  ..  Pipfile  .thoth.yaml
$ cat .thoth.yaml                                                                                                                                                                             
host: test.thoth-station.ninja
tls_verify: false
requirements_format: pipenv

runtime_environments:
  - name: fedora:28
    operating_system:
      name: fedora
      version: '28'
    python_version: '3.6'
    recommendation_type: latest
$ cat Pipfile                                                                                                                                                                                 
[dev-packages]

[packages]
pyflakes = "==0.9.2"

[requires]
python_version = "3.6"

[[source]]
name = "pypi-org"
url = "https://pypi.org/simple"
verify_ssl = true

```

**Comment by fridex** [comment]
I will close this. If the issue persists, feel free to re-open.
