### ISSUE TITLE
__init__() got an unexpected keyword argument 'recommendation_type'

### ISSUE THREAD

**Issue by fridex** [thoth-station/thamos#182]
From s2i application which integrates with Thoth:

```
+ echo 'Asking Thoth for advise...'
--
  | + thamos advise
  | Asking Thoth for advise...
  | 2019-06-26 13:26:39,461 [99] INFO     thamos: No Pipfile.lock found
  | 2019-06-26 13:26:39,604 [99] WARNING  thamos.config: Using insecure connection to API service, please contact service provider to install TLS in order to secure network traffic
  | Thamos/0.5.3 (Python 3.6.8; Linux 3.10.0-957.21.2.el7.x86_64)
  | 2019-06-26 13:26:39,623 [99] INFO     thamos.lib: Performing static analysis
  | 2019-06-26 13:26:39,626 [99] CRITICAL root: Traceback (most recent call last):
  | File "/opt/app-root/bin/thamos", line 10, in <module>
  | sys.exit(cli())
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 764, in __call__
  | return self.main(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 717, in main
  | rv = self.invoke(ctx)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
  | return _process_result(sub_ctx.command.invoke(sub_ctx))
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 956, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 555, in invoke
  | return callback(*args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/thamos/cli.py", line 341, in advise
  | no_static_analysis=no_static_analysis,
  | File "/opt/app-root/lib/python3.6/site-packages/thamos/lib.py", line 78, in wrapper
  | result = func(api_client, *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/thamos/lib.py", line 210, in advise
  | runtime_environment = RuntimeEnvironment(**runtime_environment)
  | TypeError: __init__() got an unexpected keyword argument 'recommendation_type'

```

**Comment by fridex** [comment]
Fixed in #184
