### ISSUE TITLE
AttributeError: module 'thamos.swagger_client.models' has no attribute 'Object'

### ISSUE THREAD

**Issue by CermakM** [thoth-station/thamos#193]
**Describe the bug**
`Thomas advise` triggers analysis but is not able to retrieve the results after the analysis has finished successfully, nor is it able to produce Pipfile.lock

**To Reproduce**
run `thamos advise`

**Expected behavior**
Thamos finishes without errors and creates `Pipfile.lock`

**Additional context**

<details><summary>Error traceback</summary>
<pre><code>

2019-07-16 14:32:02,781 [11446] CRITICAL root: Traceback (most recent call last):
  File "/home/macermak/.local/bin/thamos", line 10, in <module>
    sys.exit(cli())
  File "/home/macermak/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/macermak/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/macermak/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/macermak/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/macermak/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/macermak/.local/lib/python3.6/site-packages/thamos/cli.py", line 341, in advise
    no_static_analysis=no_static_analysis,
  File "/home/macermak/.local/lib/python3.6/site-packages/thamos/lib.py", line 78, in wrapper
    result = func(api_client, *args, **kwargs)
  File "/home/macermak/.local/lib/python3.6/site-packages/thamos/lib.py", line 268, in advise
    api_instance.get_advise_python, response.analysis_id
  File "/home/macermak/.local/lib/python3.6/site-packages/thamos/lib.py", line 124, in _retrieve_analysis_result
    return retrieve_func(analysis_id)
  File "/home/macermak/.local/lib/python3.6/site-packages/thamos/swagger_client/thoth/advise_api.py", line 53, in get_advise_python
    (data) = self.get_advise_python_with_http_info(analysis_id, **kwargs)  # noqa: E501
  File "/home/macermak/.local/lib/python3.6/site-packages/thamos/swagger_client/thoth/advise_api.py", line 126, in get_advise_python_with_http_info
    collection_formats=collection_formats)
  File "/home/macermak/.local/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 321, in call_api
    _preload_content, _request_timeout)
  File "/home/macermak/.local/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 160, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/home/macermak/.local/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 232, in deserialize
    return self.__deserialize(data, response_type)
  File "/home/macermak/.local/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 271, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/macermak/.local/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 614, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/home/macermak/.local/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 271, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/macermak/.local/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 614, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/home/macermak/.local/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 260, in __deserialize
    klass = getattr(thamos.swagger_client.models, klass)
AttributeError: module 'thamos.swagger_client.models' has no attribute 'Object'</code></pre>
</div>
</details>

**Comment by CermakM** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Integrate Thoth with Jupyter Notebooks [KR12]](https://trello.com/c/1v8mycDy/569-3-integrate-thoth-with-jupyter-notebooks-kr12)

**Comment by CermakM** [comment]
This is the last working commit:

https://github.com/thoth-station/thamos/commit/5299a55f9816b8bfbc5fc10251cb8036e278ed90

This commit causes the trouble:
https://github.com/thoth-station/thamos/commit/a1c63c443a7650536ee82e760ef2c59e7fa24804
