### ISSUE TITLE
Provide more information about failure when a pod runs OOM

### ISSUE THREAD

**Issue by CermakM** [thoth-station/thamos#199]
**Is your feature request related to a problem? Please describe.**
When a pod runs OOM, there is a CRITICAL error thrown (see the details).

**Describe the solution you'd like**
I'd like to be notified about the pod failure (or at least about *a* failure in the cluster).

**Additional context**
<details><summary>Error traceback</summary>
<pre><code>
2019-07-16 08:43:55,317 [20254] CRITICAL root: Traceback (most recent call last):
  File "/home/macermak/.local/bin/thamos", line 11, in <module>
    load_entry_point('thamos==0.5.3', 'console_scripts', 'thamos')()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 763, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 716, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1136, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 955, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 554, in invoke
    return callback(*args, **kwargs)
  File "/home/macermak/.local/lib/python3.7/site-packages/thamos/cli.py", line 356, in advise
    if result["report"][0][0]:
IndexError: list index out of range
</code>
</pre>
</details

**Comment by goern** [comment]
This seems to be a run time observation we could capture?!

**Comment by fridex** [comment]
This looks like not captured properly handled error of adviser in thamos. I'll try to replicate it - [this might be the fix also for this](https://github.com/thoth-station/adviser/pull/314), but not sure.

**Comment by fridex** [comment]
Observed this issue on stage with `adviser-6c135ee5cf98c04b`. Fix in #206.
