### ISSUE TITLE
Pipfile is empty after contoml exception

### ISSUE THREAD

**Issue by goern** [thoth-station/thamos#232]
**Describe the bug**
```
2019-08-21 09:53:33,613 [17662] INFO     thamos: No Pipfile.lock found
2019-08-21 09:53:34,645 [17662] WARNING  thamos.config: Using insecure connection to API service, please contact service provider to install TLS in order to secure network traffic
2019-08-21 09:53:34,656 [17662] INFO     thamos.lib: Performing static analysis of sources to gather library usage
2019-08-21 09:53:35,310 [17662] INFO     thamos.lib: Successfully submitted advise analysis 'adviser-16fe8beaf0594cb3' to 'http://stage.thoth-station.ninja/api/v1'
2019-08-21 09:56:13,970 [17662] CRITICAL root: Traceback (most recent call last):
  File "/home/goern/.local/lib/python3.7/site-packages/contoml/elements/abstracttable.py", line 22, in _enumerate_items
    yield next(non_metadata), next(non_metadata)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/goern/.local/bin/thamos", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.7/site-packages/click/core.py", line 763, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 716, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1136, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 955, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 554, in invoke
    return callback(*args, **kwargs)
  File "/home/goern/.local/lib/python3.7/site-packages/thamos/cli.py", line 379, in advise
    _write_pipfiles(pipfile, pipfile_lock)
  File "/home/goern/.local/lib/python3.7/site-packages/thamos/cli.py", line 111, in _write_pipfiles
    toml.dump(pipfile, "Pipfile", prettify=False)
  File "/home/goern/.local/lib/python3.7/site-packages/contoml/__init__.py", line 75, in dump
    fp.write(dumps(obj, prettify=prettify))
  File "/home/goern/.local/lib/python3.7/site-packages/contoml/__init__.py", line 58, in dumps
    f[k] = v
  File "/home/goern/.local/lib/python3.7/site-packages/contoml/file/file.py", line 51, in __setitem__
    self._elements.append(element_factory.create_table(value))
  File "/home/goern/.local/lib/python3.7/site-packages/contoml/elements/factory.py", line 134, in create_table
    table_element = TableElement([create_newline_element()])
  File "/home/goern/.local/lib/python3.7/site-packages/contoml/elements/table.py", line 22, in __init__
    self._check_for_duplicate_keys()
  File "/home/goern/.local/lib/python3.7/site-packages/contoml/elements/table.py", line 25, in _check_for_duplicate_keys
    if len(set(self.keys())) < len(self.keys()):
  File "/home/goern/.local/lib/python3.7/site-packages/contoml/elements/abstracttable.py", line 32, in keys
    return tuple(key for (key, _) in self.items())
  File "/home/goern/.local/lib/python3.7/site-packages/contoml/elements/abstracttable.py", line 32, in <genexpr>
    return tuple(key for (key, _) in self.items())
  File "/home/goern/.local/lib/python3.7/site-packages/contoml/elements/abstracttable.py", line 25, in items
    for (key_i, key), (value_i, value) in self._enumerate_items():
RuntimeError: generator raised StopIteration

```

after this exception is raised and not handled by `thamos` the `Pipfile` is empty.

**To Reproduce**
1. `git clone git@github.com:goern/ludus.git`
2. `cd ludus`
3. `git checkout thoth-advise-config`
2. `sudo podman run --rm -ti -v$(pwd):/opt/redhat/thoth/thamos/workdir:Z quay.io/thoth-station/thamos:v0.7.0-dev thamos advise --debug --force`

**Comment by goern** [comment]
maybe we shouldnt write any Pipfile or Pipfile.lock if any exception was raised

**Comment by fridex** [comment]
Getting this error:

```
$ sudo podman run --rm -ti -vpwd:/opt/redhat/thoth/thamos/workdir:Z quay.io/thoth-station/thamos:0.7.0-dev thamos advise --debug --force
Trying to pull quay.io/thoth-station/thamos:0.7.0-dev...ERRO[0002] Error pulling image ref //quay.io/thoth-station/thamos:0.7.0-dev: Error initializing source docker://quay.io/thoth-station/thamos:0.7.0-dev: Error reading manifest 0.7.0-dev in quay.io/thoth-station/thamos: manifest unknown: manifest unknown 
Failed
Error: unable to pull quay.io/thoth-station/thamos:0.7.0-dev: unable to pull image: Error initializing source docker://quay.io/thoth-station/thamos:0.7.0-dev: Error reading manifest 0.7.0-dev in quay.io/thoth-station/thamos: manifest unknown: manifest unknown
```

**Comment by goern** [comment]
uhhhh... missed a `v`, fixed the podman command.

**Comment by fridex** [comment]
So the issue is with a nested empty dictionary (the content under `dev-packages` is empty):

```python
>>> import contoml as toml
>>> a = {'a': {}}
>>> toml.dumps(a)
```
