### ISSUE TITLE
Thamos advise fails with Invalid state value

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thamos#350]
**Describe the bug**
While executing `thamos advise` on MOC cluster. Observed that after the adviser run is complete the `thamos advise` fails stating `ValueError: Invalid value for 'state', must not be 'None'`

**To Reproduce**
1. Step up thamos with v0.8.1
2. An app with `.thoth.yaml` configured as 
```
host: 'api.moc.thoth-station.ninja'
tls_verify: false
requirements_format: pipenv

runtime_environments:
  - name: 'rhel:8.0'
    operating_system:
      name: 'rhel'
      version: '8.0'
    python_version: '3.6'
    recommendation_type: STABLE

managers:
  - name: thoth-advise
    configuration:
      labels: [bot, kebechet]
  - name: thoth-provenance
    configuration:
      labels: [bot, kebechet]
```
3. Run the cmd: `thamos advise`

**Expected behavior**
Run successfully with a result as output.

**Observed behavior**
```
(thamos-test) hnalla@workstation ~/thoth-test/thamos-test/test $ thamos advise
2020-03-24 09:27:39,933 [1716896] WARNING  thamos.config: TLS verification turned off, its highly recommended to use a secured connection, see configuration file for configuration options
2020-03-24 09:27:39,958 [1716896] INFO     thamos.lib: Performing static analysis of sources to gather library usage
2020-03-24 09:27:39,959 [1716896] WARNING  thamos.lib: No library usage was aggregated - no Python sources found
2020-03-24 09:27:45,629 [1716896] INFO     thamos.lib: Successfully submitted advise analysis 'adviser-852df688' to 'https://api.moc.thoth-station.ninja/api/v1'
2020-03-24 09:27:46,938 [1716896] CRITICAL root: Traceback (most recent call last):
  File "/home/hnalla/.local/share/virtualenvs/thamos-test-hQVFFVj9/bin/thamos", line 8, in <module>
    sys.exit(cli())
  File "/home/hnalla/.local/share/virtualenvs/thamos-test-hQVFFVj9/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/hnalla/.local/share/virtualenvs/thamos-test-hQVFFVj9/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/hnalla/.local/share/virtualenvs/thamos-test-hQVFFVj9/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hnalla/.local/share/virtualenvs/thamos-test-hQVFFVj9/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hnalla/.local/share/virtualenvs/thamos-test-hQVFFVj9/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/hnalla/.local/share/virtualenvs/thamos-test-hQVFFVj9/lib/python3.6/site-packages/thamos/cli.py", line 372, in advise
    no_static_analysis=no_static_analysis,
  File "/home/hnalla/.local/share/virtualenvs/thamos-test-hQVFFVj9/lib/python3.6/site-packages/thamos/lib.py", line 81, in wrapper
    result = func(api_client, *args, **kwargs)
  File "/home/hnalla/.local/share/virtualenvs/thamos-test-hQVFFVj9/lib/python3.6/site-packages/thamos/lib.py", line 322, in advise
    _wait_for_analysis(api_instance.get_advise_python_status, response.analysis_id)
  File "/home/hnalla/.local/share/virtualenvs/thamos-test-hQVFFVj9/lib/python3.6/site-packages/thamos/lib.py", line 108, in _wait_for_analysis
    response = status_func(analysis_id)
  File "/home/hnalla/.local/share/virtualenvs/thamos-test-hQVFFVj9/lib/python3.6/site-packages/thamos/swagger_client/thoth/advise_api.py", line 239, in get_advise_python_status
    (data) = self.get_advise_python_status_with_http_info(analysis_id, **kwargs)  # noqa: E501
  File "/home/hnalla/.local/share/virtualenvs/thamos-test-hQVFFVj9/lib/python3.6/site-packages/thamos/swagger_client/thoth/advise_api.py", line 312, in get_advise_python_status_with_http_info
    collection_formats=collection_formats)
  File "/home/hnalla/.local/share/virtualenvs/thamos-test-hQVFFVj9/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 321, in call_api
    _preload_content, _request_timeout)
  File "/home/hnalla/.local/share/virtualenvs/thamos-test-hQVFFVj9/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 160, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/home/hnalla/.local/share/virtualenvs/thamos-test-hQVFFVj9/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 232, in deserialize
    return self.__deserialize(data, response_type)
  File "/home/hnalla/.local/share/virtualenvs/thamos-test-hQVFFVj9/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 271, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/hnalla/.local/share/virtualenvs/thamos-test-hQVFFVj9/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 614, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/home/hnalla/.local/share/virtualenvs/thamos-test-hQVFFVj9/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 271, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/hnalla/.local/share/virtualenvs/thamos-test-hQVFFVj9/lib/python3.6/site-packages/thamos/swagger_client/api_client.py", line 616, in __deserialize_model
    instance = klass(**kwargs)
  File "/home/hnalla/.local/share/virtualenvs/thamos-test-hQVFFVj9/lib/python3.6/site-packages/thamos/swagger_client/models/analysis_status_response_status.py", line 63, in __init__
    self.state = state
  File "/home/hnalla/.local/share/virtualenvs/thamos-test-hQVFFVj9/lib/python3.6/site-packages/thamos/swagger_client/models/analysis_status_response_status.py", line 199, in state
    raise ValueError("Invalid value for `state`, must not be `None`")  # noqa: E501
ValueError: Invalid value for `state`, must not be `None`
```

**Additional context**

**Comment by fridex** [comment]
Yes, it should not be none based on openapi:

https://github.com/thoth-station/user-api/blob/34cb986cbee8464600f55d14234a80ac5e737cc1/openapi/openapi.yaml#L2016-L2018

Do you use Argo to schedule workload?

**Comment by harshad16** [comment]
@fridex workload-operator is being used in the cluster.
 I will try to update the user-api image and check again.

**Comment by fridex** [comment]
We haven't touch this logic for a while so it might be the same issue, but worth trying.

**Comment by fridex** [comment]
Hm... maybe - could you please check what's the raw JSON response for the given adviser id on the status endpoint?

**Comment by saisankargochhayat** [comment]
It seem's to give the same error - `ValueError: Invalid value for `state`, must not be `None``
Here is a json response - 
```
{
  "parameters": {
    "analysis_id": "adviser-7c3035d5"
  },
  "status": {
    "completions": 1,
    "finished_at": "2020-03-24T15:37:19Z",
    "pods": [
      {
        "container": "1714b6acc9e3136da9bc8442858b5b345df1038330457220962e951a768c8152",
        "exit_code": 0,
        "finished_at": "2020-03-24T15:37:13Z",
        "reason": "Completed",
        "started_at": "2020-03-24T15:37:02Z",
        "state": "terminated"
      }
    ],
    "started_at": "2020-03-24T15:36:49Z",
    "succeeded": 1
  }
}
```
It seem's to fail on thamos cli even before the advisor container is created.

**Comment by fridex** [comment]
The response should report back what's inside `.pods[0]` (pod status), not the whole job status:

```
{
  "parameters": {
    "analysis_id": "adviser-7c3035d5"
  },
  "status": {
      "container": "1714b6acc9e3136da9bc8442858b5b345df1038330457220962e951a768c8152",
      "exit_code": 0,
      "finished_at": "2020-03-24T15:37:13Z",
      "reason": "Completed",
      "started_at": "2020-03-24T15:37:02Z",
      "state": "terminated"
    }
}
```

https://github.com/thoth-station/user-api/blob/34cb986cbee8464600f55d14234a80ac5e737cc1/thoth/user_api/api_v1.py#L812

**Comment by harshad16** [comment]
> Hm... maybe - could you please check what's the raw JSON response for the given adviser id on the status endpoint?

Is this what i should check : 
curl -X GET "https://api.moc.thoth-station.ninja/api/v1/advise/python/adviser-852df688" -H "accept: application/json"

It gives the correct result back.

**Comment by fridex** [comment]
The result obtaining endpoint looks good. :+1: 

The issue is in the status obtaining endpoint. The status endpoint does not correspond to the schema declared in openapi:

https://github.com/thoth-station/user-api/blob/34cb986cbee8464600f55d14234a80ac5e737cc1/openapi/openapi.yaml#L1981-L2021

This causes "None" values being propagated when the response is serialized in thamos (client side). The fix is to return pod stastus, not job status from API endpoints:

```diff
-        status = _OPENSHIFT.get_job_status_report(job_id, namespace=namespace)
+        status = _OPENSHIFT.get_job_status_report(job_id, namespace=namespace)["pods"][0]
```

in https://github.com/thoth-station/user-api/blob/34cb986cbee8464600f55d14234a80ac5e737cc1/thoth/user_api/api_v1.py#L812
