### ISSUE TITLE
Issue when running thamos_using_config() with src_path=None

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thamos#838]
**Describe the bug**
Issue when running thamos_using_config() with src_path=None.

**To Reproduce**
```
import json

from thamos.config import _Configuration
from thoth.common.enums import ThothAdviserIntegrationEnum
from thamos.lib import advise_using_config

thoth_yaml_config = _Configuration()

thoth_yaml_config.load_config()
print(thoth_yaml_config.content)
print(thoth_yaml_config.config_path)

response = advise_using_config(
    pipfile="[[source]]\nurl = \"https://pypi.python.org/simple\"\nverify_ssl = true\nname = \"pypi\"\n\n[packages]\ndaiquiri = \"*\"\n\n[dev-packages]\n",
    pipfile_lock="pipfile_lock_str",
    config=json.dumps(thoth_yaml_config.content),
    github_event_type="thoth_thamos_advise",
    github_check_run_id=2362544688,
    github_installation_id=6181026,
    github_base_repo_url="https://api.github.com/repos/thoth-station/integration-tests",
    origin="https://github.com/thoth-station/integration-tests",
    source_type=ThothAdviserIntegrationEnum.GITHUB_APP,
    nowait=True,
)
```

**Expected behavior**
I expect https://github.com/thoth-station/thamos/blob/003f6a22c411fba48566f2e9fc5c93dbf2be17be/thamos/lib.py#L351 to not give `None`.

**Screenshots**
```
{'host': 'khemenu.thoth-station.ninja', 'tls_verify': True, 'requirements_format': 'pipenv', 'runtime_environments': [{'name': 'ubi8', 'operating_system': {'name': 'ubi', 'version': '8'}, 'python_version': '3.6', 'recommendation_type': 'latest'}], 'managers': [{'name': 'update', 'configuration': {'labels': ['bot']}}, {'name': 'info'}, {'name': 'version', 'configuration': {'maintainers': ['fridex', 'goern', 'harshad16', 'pacospace', 'sesheta'], 'assignees': ['sesheta'], 'labels': ['bot'], 'changelog_file': True}}]}
/home/fmurdaca/work/aicoe/workflow-helpers
Traceback (most recent call last):
  File "test/test.py", line 24, in <module>
    nowait=True,
  File "/home/fmurdaca/.local/share/virtualenvs/workflow-helpers-CZavPByB/lib/python3.6/site-packages/thamos/lib.py", line 370, in advise_using_config
    source_type=source_type,
  File "/home/fmurdaca/.local/share/virtualenvs/workflow-helpers-CZavPByB/lib/python3.6/site-packages/thamos/lib.py", line 108, in wrapper
    result = func(api_client, *args, **kwargs)
  File "/home/fmurdaca/.local/share/virtualenvs/workflow-helpers-CZavPByB/lib/python3.6/site-packages/thamos/lib.py", line 438, in advise
    library_usage = _get_static_analysis(src_path)
  File "/home/fmurdaca/.local/share/virtualenvs/workflow-helpers-CZavPByB/lib/python3.6/site-packages/thamos/lib.py", line 273, in _get_static_analysis
    src_path, ignore_errors=True, without_standard_imports=True
  File "/home/fmurdaca/.local/share/virtualenvs/workflow-helpers-CZavPByB/lib/python3.6/site-packages/invectio/lib.py", line 360, in gather_library_usage
    path, ignore_errors=ignore_errors
  File "/home/fmurdaca/.local/share/virtualenvs/workflow-helpers-CZavPByB/lib/python3.6/site-packages/invectio/lib.py", line 328, in _iter_python_file_ast
    for python_file in _get_python_files(path):
  File "/home/fmurdaca/.local/share/virtualenvs/workflow-helpers-CZavPByB/lib/python3.6/site-packages/invectio/lib.py", line 313, in _get_python_files
    if os.path.isfile(path):
  File "/usr/lib64/python3.6/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Additional context**

**Comment by fridex** [comment]
The behavior of having sources checked is controlled using `no_static_analysis` flag. We can raise an error sooner with a more appropriate exception if needed.

**Comment by fridex** [comment]
@pacospace Is there anything else to be done for this one or should we close it?

**Comment by pacospace** [comment]
> @pacospace Is there anything else to be done for this one or should we close it?

If I want to use this method to have an advise and I submit static analysis using `no_static_analysis=False`, then I need to set `src_path` also to some value, for example `src_path="."`, otherwise, the method will fail with the error above.

if this is the expected behaviour of this method: https://github.com/thoth-station/workflow-helpers/blob/0772be80f5a68d24c7f3ed6c95cf59bd2a0270fc/qeb_thamos_advise.py#L132 then yes, we can close this.
